; This file is for the FamiStudio Sound Engine and was generated by FamiStudio

.export _sounds=sounds

sounds:
	.word @ntsc
	.word @pal
@ntsc:
	.word @sfx_ntsc_beep0
	.word @sfx_ntsc_beep1
	.word @sfx_ntsc_bleep0
	.word @sfx_ntsc_bleep1
	.word @sfx_ntsc_error0
	.word @sfx_ntsc_error1
	.word @sfx_ntsc_explosion
	.word @sfx_ntsc_hurt
	.word @sfx_ntsc_jump
	.word @sfx_ntsc_pause
	.word @sfx_ntsc_shoot
	.word @sfx_ntsc_start0
	.word @sfx_ntsc_start1
	.word @sfx_ntsc_startalt

@pal:
	.word @sfx_pal_beep0
	.word @sfx_pal_beep1
	.word @sfx_pal_bleep0
	.word @sfx_pal_bleep1
	.word @sfx_pal_error0
	.word @sfx_pal_error1
	.word @sfx_pal_explosion
	.word @sfx_pal_hurt
	.word @sfx_pal_jump
	.word @sfx_pal_pause
	.word @sfx_pal_shoot
	.word @sfx_pal_start0
	.word @sfx_pal_start1
	.word @sfx_pal_startalt

@sfx_ntsc_beep0:
	.byte $84,$d5,$85,$00,$83,$3c,$89,$f0,$03,$00
@sfx_ntsc_beep1:
	.byte $87,$8e,$88,$00,$86,$8f,$89,$f0,$07,$00
@sfx_ntsc_bleep0:
	.byte $81,$34,$82,$00,$80,$3a,$89,$f0,$03,$00
@sfx_ntsc_bleep1:
	.byte $81,$9d,$82,$05,$80,$3f,$89,$f0,$01,$81,$f8,$82,$03,$01,$81,$ce
	.byte $82,$02,$01,$81,$fb,$82,$01,$01,$81,$67,$01,$81,$fd,$82,$00,$01
	.byte $81,$c9,$01,$81,$9f,$00
@sfx_ntsc_error0:
	.byte $81,$80,$82,$02,$80,$3f,$89,$f0,$02,$81,$a6,$05,$00
@sfx_ntsc_error1:
	.byte $87,$f8,$88,$03,$86,$8f,$89,$f0,$07,$00
@sfx_ntsc_explosion:
	.byte $8a,$0e,$89,$3f,$01,$8a,$0d,$89,$3c,$01,$8a,$0c,$89,$39,$01,$8a
	.byte $0b,$89,$36,$01,$8a,$0a,$89,$33,$01,$00
@sfx_ntsc_hurt:
	.byte $87,$a6,$88,$02,$86,$8f,$89,$f0,$01,$87,$56,$88,$03,$01,$87,$f9
	.byte $88,$02,$01,$87,$f8,$88,$03,$04,$00
@sfx_ntsc_jump:
	.byte $81,$d5,$82,$00,$80,$3f,$89,$f0,$01,$81,$bd,$01,$81,$a9,$01,$81
	.byte $8e,$01,$81,$70,$07,$00
@sfx_ntsc_pause:
	.byte $84,$46,$85,$00,$83,$3d,$89,$f0,$01,$84,$3f,$04,$00
@sfx_ntsc_shoot:
	.byte $81,$54,$82,$00,$80,$3e,$89,$f0,$01,$81,$7e,$01,$81,$a9,$01,$81
	.byte $d5,$04,$00
@sfx_ntsc_start0:
	.byte $81,$d5,$82,$00,$80,$3d,$89,$f0,$02,$81,$a9,$02,$81,$8e,$02,$81
	.byte $6a,$80,$3f,$09,$00
@sfx_ntsc_start1:
	.byte $81,$3a,$82,$02,$80,$3f,$89,$f0,$01,$81,$ce,$01,$81,$89,$82,$03
	.byte $01,$81,$74,$82,$04,$01,$81,$9d,$82,$05,$01,$81,$13,$82,$07,$01
	.byte $81,$ff,$02,$81,$00,$82,$00,$07,$00
@sfx_ntsc_startalt:
	.byte $81,$34,$82,$00,$80,$3f,$89,$f0,$0f,$00
@sfx_pal_beep0:
	.byte $84,$c6,$85,$00,$83,$3c,$89,$f0,$03,$00
@sfx_pal_beep1:
	.byte $87,$84,$88,$00,$86,$8f,$89,$f0,$07,$00
@sfx_pal_bleep0:
	.byte $81,$31,$82,$00,$80,$3a,$89,$f0,$03,$00
@sfx_pal_bleep1:
	.byte $81,$37,$82,$05,$80,$3f,$89,$f0,$01,$81,$b0,$82,$03,$01,$81,$9b
	.byte $82,$02,$01,$81,$d7,$82,$01,$01,$81,$4d,$01,$81,$eb,$82,$00,$01
	.byte $81,$ba,$01,$81,$94,$00
@sfx_pal_error0:
	.byte $81,$52,$82,$02,$80,$3f,$89,$f0,$02,$81,$75,$05,$00
@sfx_pal_error1:
	.byte $87,$b0,$88,$03,$86,$8f,$89,$f0,$07,$00
@sfx_pal_explosion:
	.byte $8a,$0e,$89,$3f,$01,$8a,$0d,$89,$3c,$01,$8a,$0c,$89,$39,$01,$8a
	.byte $0b,$89,$36,$01,$8a,$0a,$89,$33,$01,$00
@sfx_pal_hurt:
	.byte $87,$75,$88,$02,$86,$8f,$89,$f0,$01,$87,$19,$88,$03,$01,$87,$c3
	.byte $88,$02,$01,$87,$b0,$88,$03,$04,$00
@sfx_pal_jump:
	.byte $81,$c6,$82,$00,$80,$3f,$89,$f0,$01,$81,$b0,$01,$81,$9d,$01,$81
	.byte $84,$01,$81,$68,$07,$00
@sfx_pal_pause:
	.byte $84,$41,$85,$00,$83,$3d,$89,$f0,$01,$84,$3a,$04,$00
@sfx_pal_shoot:
	.byte $81,$4e,$82,$00,$80,$3e,$89,$f0,$01,$81,$75,$01,$81,$9d,$01,$81
	.byte $c6,$04,$00
@sfx_pal_start0:
	.byte $81,$c6,$82,$00,$80,$3d,$89,$f0,$02,$81,$9d,$02,$81,$84,$02,$81
	.byte $62,$80,$3f,$09,$00
@sfx_pal_start1:
	.byte $81,$11,$82,$02,$80,$3f,$89,$f0,$01,$81,$9b,$01,$81,$49,$82,$03
	.byte $01,$81,$23,$82,$04,$01,$81,$37,$82,$05,$01,$81,$92,$82,$06,$01
	.byte $81,$ff,$82,$07,$02,$81,$00,$82,$00,$07,$00
@sfx_pal_startalt:
	.byte $81,$31,$82,$00,$80,$3f,$89,$f0,$0f,$00

.export sounds
