; This file is for the FamiStudio Sound Engine and was generated by FamiStudio
; Required flags for 10000000_in_1_(menu):
; FAMISTUDIO_USE_VOLUME_TRACK = 1
; FAMISTUDIO_USE_PITCH_TRACK = 1

.export _music_data_10000000_in_1_menu:=music_data_10000000_in_1_menu

music_data_10000000_in_1_menu:
	.byte 1
	.word @instruments
	.word @samples-4
; 00 : Song 1
	.word @song0ch0
	.word @song0ch1
	.word @song0ch2
	.word @song0ch3
	.word @song0ch4
	.byte .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), 0, 0

.export music_data_10000000_in_1_menu
.global FAMISTUDIO_DPCM_PTR

@instruments:
	.word @env1,@env2,@env3,@env0 ; 00 : Duty 0
	.word @env1,@env2,@env4,@env0 ; 01 : Duty 2
	.word @env1,@env2,@env5,@env0 ; 02 : Duty 1

@env0:
	.byte $00,$c0,$7f,$00,$02
@env1:
	.byte $00,$cf,$7f,$00,$02
@env2:
	.byte $c0,$7f,$00,$01
@env3:
	.byte $7f,$00,$00
@env4:
	.byte $c2,$7f,$00,$00
@env5:
	.byte $c1,$7f,$00,$00

@samples:

@tempo_env_1_mid:
	.byte $03,$05,$80

@song0ch0:
@song0ch0loop:
	.byte $47, .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), $7c, $4e, $ff, $84, $25
@song0ref10:
	.byte $83
@song0ref11:
	.byte $7e, $87
@song0ref13:
	.byte $7d, $85
@song0ref15:
	.byte $7c, $87, $7b, $87, $7a, $87, $79, $85, $78, $87, $77, $87, $76, $87, $75, $85, $74, $87, $73, $87, $72, $87, $71, $85
	.byte $00, $e7, $7e, $29, $85
	.byte $41, $0b
	.word @song0ref13
	.byte $72, $85, $4e, $00, $27
@song0ref52:
	.byte $7e, $87, $7d, $85, $7c, $87, $7e, $4e, $ff, $25, $85, $7d, $87, $7c, $85, $7b, $81, $4e, $00, $27, $83, $7e, $87, $7d
	.byte $87, $7c, $81, $4e, $ff, $25
@song0ref82:
	.byte $81
@song0ref83:
	.byte $7e, $87
@song0ref85:
	.byte $7d, $87, $7c, $87, $7b, $85, $7a, $87
@song0ref93:
	.byte $79, $87, $78, $87, $77, $85, $76, $87, $75, $87, $74, $87, $73, $85, $72, $87, $71, $87, $00, $8d, $48, $a9
@song0ref115:
	.byte $4e, $00, $81, $7e, $27, $85, $7d, $85, $7c, $87, $7e, $4e, $ff, $29, $85, $7d, $87, $7c, $85, $7b, $81, $25, $83, $7e
	.byte $87, $7d, $87, $7c, $87
@song0ref144:
	.byte $7e
@song0ref145:
	.byte $85
@song0ref146:
	.byte $7d, $87
@song0ref148:
	.byte $7c, $87, $7b, $87, $7a, $85
@song0ref154:
	.byte $79, $87, $78, $87, $77, $87, $76, $85, $75, $87, $74, $87, $73, $87, $72, $85, $71, $87, $00
@song0ref173:
	.byte $e7, $7e, $25, $83, $7d, $87, $7c, $87, $7b, $81, $4e, $00, $20, $83, $7e, $85, $7d, $87
	.byte $41, $0a
	.word @song0ref15
	.byte $7e, $24, $85, $7d, $85, $7c, $87, $7b, $87, $7a, $87, $79, $85, $78, $83, $27, $81, $7e, $87, $48
@song0ref214:
	.byte $7d, $87
@song0ref216:
	.byte $7c, $85, $7b, $87, $7a, $87, $79, $87, $78, $85, $77, $87, $76, $87, $75, $87, $74, $85, $73, $87, $72, $81, $4e, $ff
	.byte $29, $83, $7e, $87, $7d, $85, $7c, $87, $7b, $87, $7a, $87, $79, $83, $25, $7e, $87, $7d, $87, $7c, $87, $7b, $85, $7a
	.byte $87, $79, $87, $7e, $87
	.byte $41, $0b
	.word @song0ref214
	.byte $72, $87, $71, $87, $00, $eb
@song0ref278:
	.byte $4e, $00, $81, $7e, $27, $85, $7d, $85, $7c
@song0ref287:
	.byte $87
@song0ref288:
	.byte $7e, $4e, $ff, $25
@song0ref292:
	.byte $85, $7d, $87, $7c, $85, $7b, $87, $7a, $87, $79, $87, $78, $85, $77, $87, $76, $87, $75, $87, $74, $87, $73, $85, $48
@song0ref316:
	.byte $72, $87, $71, $87, $00, $eb, $4e, $00, $81, $7e, $1d, $85, $7d, $87, $7c, $85, $7b, $87, $7a, $87, $79, $87, $7e, $1e
	.byte $83, $7d, $87, $7c, $87, $7b, $81, $20, $83
	.byte $41, $0c
	.word @song0ref144
	.byte $72, $87, $71, $85, $00, $ff, $c7, $48, $ff, $ff
	.byte $41, $0c
	.word @song0ref287
	.byte $74, $85, $73, $87, $72, $87, $71, $87, $00, $ff, $83, $7e, $29, $83, $48, $81
@song0ref381:
	.byte $7d, $87, $7c, $87, $7b, $85, $7a, $87, $79, $87, $78, $87, $77, $85, $76, $87, $75, $83, $00, $89, $7e, $4e, $00, $27
	.byte $83, $7d, $85, $4e, $ff, $25, $7e, $87, $7d, $81, $4e, $00, $27, $83, $7e, $85, $4e, $ff, $25, $85, $7d, $87, $7c, $87
	.byte $7b, $85, $7a, $87
	.byte $41, $0a
	.word @song0ref154
@song0ref436:
	.byte $d3, $4e, $00, $83, $7e, $27, $85, $7d, $87, $7c, $85, $7b, $87, $7a, $87, $79, $85, $4e, $ff, $29, $7e, $85, $7d, $83
	.byte $25, $81, $7e, $8f, $7d, $83, $4e, $00, $27, $7e, $87, $7d, $81, $22
	.byte $41, $0a
	.word @song0ref10
	.byte $75, $87, $74, $85, $73, $87, $72, $87, $71, $83, $48, $83, $00, $cf, $7e, $4e, $ff, $25, $85, $7d, $85, $7c, $87, $7e
	.byte $4e, $00, $20
	.byte $41, $0a
	.word @song0ref292
	.byte $74, $85, $73, $87, $72, $85, $24, $7e, $87, $7d, $85, $7c, $87, $7b, $87, $7a, $87, $79, $87, $78, $27, $83
	.byte $41, $0f
	.word @song0ref83
@song0ref532:
	.byte $a3, $7e, $4e, $ff, $29, $83, $7d, $87, $7c, $83, $25, $81, $7e, $87, $7d, $85, $7c, $85, $4e, $00, $27, $7e, $87, $7d
	.byte $87, $7c, $85, $7e, $4e, $ff, $25, $85, $7d, $87, $7c, $87, $7b, $85, $7a, $87, $79, $83, $48, $83, $78, $87, $77, $85
	.byte $76, $87, $75, $87, $74, $87, $73, $87, $72, $85, $71, $87, $00, $a3, $7e, $29, $85, $7d, $85, $7c, $87, $7b, $87, $7a
	.byte $85, $4e, $00, $27, $7e, $85, $7d, $83, $4e, $ff, $25, $81, $7e, $87, $4e, $00, $27, $85, $7d, $83, $4e, $ff, $25
	.byte $41, $0f
	.word @song0ref83
	.byte $ff, $85, $7e, $25, $83, $7d, $87, $7c, $87, $7b, $87, $7a, $85, $79, $87, $7e, $2c, $85, $7d, $87, $7c, $85, $7b, $87
	.byte $7a, $87, $79, $87, $78, $81, $48, $83, $77, $87, $76, $87, $75, $87, $74, $85, $73, $87, $72, $87, $71, $87, $00, $ff
	.byte $b3, $4e, $00, $85, $7e, $30, $83
	.byte $41, $0e
	.word @song0ref146
@song0ref688:
	.byte $a3, $7e, $2e, $85, $30, $83, $7d, $85, $2e, $7e, $87, $7d, $81, $4e, $ff, $2c, $83, $7e, $85, $4e, $00, $2e, $85, $7d
	.byte $83, $4e, $ff, $2c, $81, $7e, $87, $4e, $00, $2a, $85, $7d, $85, $7c, $87, $7b, $87, $7a, $87, $79, $85, $78, $87, $77
	.byte $81, $48, $85, $76, $87, $75, $83, $4e, $ff, $29
	.byte $41, $0c
	.word @song0ref83
	.byte $72, $83
@song0ref751:
	.byte $25, $81, $7e, $87, $7d, $87, $7c, $85, $7b, $87, $7a, $87, $79, $85, $4e, $00, $20, $7e, $85, $7d, $87, $7c, $87, $7b
	.byte $87, $7a, $85, $79, $87, $78, $87, $77, $87, $76, $87, $75, $85, $74, $87, $73, $87, $72, $87, $71, $85, $00, $ff, $ef
	.byte $48, $d9, $7e, $4e, $ff, $25, $83
	.byte $41, $0b
	.word @song0ref146
	.byte $00, $89, $71
@song0ref812:
	.byte $4e, $00, $27, $7e, $87, $7d, $81, $4e, $ff, $25, $83, $7e, $85, $4e, $00, $27, $85, $7d, $83, $4e, $ff, $25, $81
	.byte $41, $0d
	.word @song0ref11
	.byte $71, $87, $00, $9f, $4e, $00, $81, $7e, $24, $85, $7d, $87, $7c, $87, $7b, $85, $7a, $83, $20, $81, $7e, $87, $7d, $87
	.byte $7c, $85, $7b, $87, $7a, $81, $1d, $83, $7e, $87, $7d, $85, $7c, $87, $7b, $87, $7a, $87, $79, $85, $78, $87, $77, $87
	.byte $48, $76, $87, $75, $85, $74, $87, $73, $87, $72, $87, $71, $85, $00, $d1, $7e, $24, $85
	.byte $41, $0e
	.word @song0ref13
	.byte $a3, $7e, $22, $85, $7d, $87, $7c, $85, $7b, $81, $1e, $83, $7e, $87, $7d, $87, $7c, $81, $1b
	.byte $41, $0c
	.word @song0ref82
	.byte $73, $87, $00, $9b, $7e, $27, $83, $7d, $87, $7c, $87, $7b, $87, $7a, $85, $79, $87, $78, $87, $77, $87, $76, $85, $48
	.byte $75, $87, $74, $87, $73, $87, $72, $85, $71, $87, $00, $a3, $7e, $4e, $ff, $29, $85, $7d, $85, $7c, $85, $4e, $00, $27
	.byte $7e, $87, $7d, $87, $7c, $85, $7e, $4e, $ff, $29, $85, $7d, $87, $7c, $87, $7e, $2c, $83, $7d, $87, $7c, $87, $7b, $81
	.byte $4e, $00, $2e, $83, $7e, $85, $7d, $87, $7c, $87, $7b, $87, $7e, $4e, $ff, $29, $85, $7d, $83
	.byte $41, $0b
	.word @song0ref812
	.byte $7e, $87
	.byte $41, $0b
	.word @song0ref214
	.byte $72, $87, $71, $87, $00, $ff, $91, $48, $ff, $ff, $99, $4e, $00, $83, $7e, $1e, $85, $7d, $87, $7c, $83, $20
@song0ref1050:
	.byte $81, $7e, $87, $7d, $85, $7c, $87, $7b, $87, $7a, $87, $79, $85, $78, $87, $77, $87, $76, $87, $7e, $22, $83, $7d, $87
	.byte $7c, $87, $7b, $81, $4e, $ff, $25, $83, $7e, $85, $7d, $87, $7c, $83, $4e, $00, $24
	.byte $41, $0a
	.word @song0ref1050
	.byte $75, $85, $74, $85, $48, $81, $73, $87, $72, $81, $4e, $ff, $25, $83, $7e, $85, $7d, $87, $7c, $83, $4e, $00, $24, $81
	.byte $7e, $87, $7d, $85, $7c, $85, $22
@song0ref1125:
	.byte $7e, $87, $7d, $87, $7c, $85, $7b, $87, $7a, $87, $79, $87, $78, $87, $77, $85, $76, $87, $75, $87, $74, $87, $73, $85
	.byte $72, $83, $1e, $81, $7e, $87, $7d, $87, $7c, $83, $22, $7e, $87, $7d, $87, $7c, $85, $20
	.byte $41, $0f
	.word @song0ref144
	.byte $a3, $7e, $1e, $85, $7d, $85, $7c, $87
@song0ref1178:
	.byte $7b, $81, $20, $83, $7e, $87, $7d, $87, $7c, $85, $7b, $87, $7a, $87, $79, $87, $78, $85, $77, $87, $76, $85, $22
	.byte $41, $0b
	.word @song0ref52
	.byte $7d, $83, $48, $83
	.byte $41, $0a
	.word @song0ref216
	.byte $7e, $87, $7d, $87, $7c, $85, $7b, $81, $4e, $ff, $25, $83, $7e, $87, $7d, $87, $7c, $81, $29, $81, $7e, $87, $7d, $87
	.byte $7c, $83, $2c, $81, $7e, $85, $7d, $87, $7c, $87, $7b, $87, $7a, $87, $79, $85, $78, $87, $77, $87, $76, $87, $7e, $4e
	.byte $00, $2e, $83, $7d, $87, $7c, $87, $7b, $81, $4e, $ff, $29, $83, $7e, $85, $7d, $87, $7c, $83, $25, $81, $7e, $87, $4e
	.byte $00, $27, $83, $7d, $85, $4e, $ff, $25, $7e, $87
	.byte $41, $0b
	.word @song0ref214
	.byte $72, $83, $00, $95, $4e, $00, $81, $7e, $1e, $85, $7d, $87, $7c, $85, $7e, $20, $85, $7d, $87, $7c, $87, $7b, $85, $7a
	.byte $87, $79, $87, $78, $87, $77, $87, $76, $85, $75, $83, $48, $22, $81, $7e, $87, $7d, $87, $7c, $83, $4e, $ff, $25, $7e
	.byte $87, $7d, $87, $7c, $85, $4e, $00, $24
	.byte $41, $0c
	.word @song0ref144
	.byte $72, $83, $4e, $ff, $25, $7e, $87, $7d, $87, $7c, $85, $4e, $00, $24, $7e, $85, $7d, $87, $7c, $87, $7e, $22, $85
	.byte $41, $0b
	.word @song0ref13
	.byte $72, $85, $1e, $7e, $87, $7d, $85, $7c, $87, $7e, $22, $85, $7d, $87, $7c, $85
	.byte $41, $0b
	.word @song0ref1178
	.byte $76, $87, $75, $87, $74, $85, $73, $87, $72, $87, $71, $87, $00, $a1, $7e, $1e, $85, $7d, $87, $7c, $83, $20, $81, $7e
	.byte $81, $48, $83, $7d, $87, $7c, $87, $7b, $87, $7a, $85, $79, $87, $78, $87, $77, $87, $76, $87, $75, $22, $83, $7e, $87
	.byte $7d, $87, $7c, $81, $4e, $ff, $25, $83, $7e, $85, $7d, $87, $7c, $83, $4e, $00, $27
	.byte $41, $0a
	.word @song0ref1050
	.byte $75, $85, $74, $87, $73, $87, $72, $81, $4e, $ff, $29, $83, $7e, $85, $7d, $87, $7c, $83, $4e, $00, $27, $81, $7e, $87
	.byte $7d, $85, $7c, $85, $4e, $ff, $25, $7e, $87
	.byte $41, $0b
	.word @song0ref214
	.byte $72, $87, $71, $87, $00, $ff, $8d, $48, $ab, $7e, $25, $83
	.byte $41, $0f
	.word @song0ref146
	.byte $7e, $29, $85
	.byte $41, $0b
	.word @song0ref13
	.byte $72, $85, $4e, $00, $27, $7e, $85, $7d, $87, $7c, $87, $7e, $4e, $ff, $25, $85, $7d, $85, $7c, $87, $7b, $81, $4e, $00
	.byte $27, $83, $7e, $87, $7d, $85, $7c, $83, $4e, $ff, $25, $81
	.byte $41, $0b
	.word @song0ref1125
	.byte $48, $73, $85, $72, $87, $71, $87, $00, $b7
	.byte $41, $0e
	.word @song0ref115
	.byte $7c, $85
	.byte $41, $0f
	.word @song0ref83
	.byte $41, $0a
	.word @song0ref173
	.byte $41, $0a
	.word @song0ref148
	.byte $7e, $24, $83, $7d, $87, $7c, $87, $48, $7b, $87, $7a, $85, $79, $87, $78, $83, $27, $81, $7e, $87
	.byte $41, $1c
	.word @song0ref214
	.byte $41, $0e
	.word @song0ref13
	.byte $ed
	.byte $41, $0d
	.word @song0ref278
	.byte $48, $77, $87, $76, $87, $75, $87, $74, $85, $73, $87
	.byte $41, $13
	.word @song0ref316
	.byte $41, $0f
	.word @song0ref144
	.byte $ff, $a1, $48, $ff, $ff, $ad
	.byte $41, $0b
	.word @song0ref288
	.byte $74, $85, $73, $87, $72, $87, $71, $87, $00, $e3, $48, $9f, $7e, $29, $85
	.byte $41, $1a
	.word @song0ref381
	.byte $41, $0a
	.word @song0ref93
	.byte $41, $14
	.word @song0ref436
	.byte $83, $7e, $87, $7d, $85, $7c, $87, $7b, $87, $7a, $87, $79, $85, $78, $87, $77, $87, $76, $83, $48, $83, $75, $85, $74
	.byte $87, $73, $87, $72, $87, $71, $85, $00, $d1, $7e, $4e, $ff, $25, $85, $7d, $85, $7c, $87, $7e, $4e, $00, $20
	.byte $41, $0a
	.word @song0ref292
	.byte $74, $85, $73, $87, $72, $85, $24, $7e, $87, $7d, $85, $7c, $87, $7b, $87, $7a, $87, $79, $85, $78, $81, $27, $83, $7e
	.byte $87
	.byte $41, $0b
	.word @song0ref214
	.byte $72, $87, $71, $87, $00
	.byte $41, $0f
	.word @song0ref532
	.byte $81, $48, $83
	.byte $41, $0e
	.word @song0ref85
	.byte $a3, $7e, $29, $83, $7d, $87, $7c, $87, $7b, $87, $7a, $85, $7e, $4e, $00, $27, $85, $7d, $83, $4e, $ff, $25, $81, $7e
	.byte $87, $4e, $00, $27, $85, $7d, $83, $4e, $ff, $25
	.byte $41, $0f
	.word @song0ref83
	.byte $ff, $83, $7e, $25, $85, $7d, $87, $7c, $87, $7b, $85, $7a, $87, $79, $87, $7e, $2c, $85, $7d, $81, $48, $85
	.byte $41, $0a
	.word @song0ref216
	.byte $72, $87, $71, $87, $00, $ff, $b3, $4e, $00, $83, $7e, $30
	.byte $41, $0f
	.word @song0ref145
	.byte $41, $13
	.word @song0ref688
	.byte $83, $7d, $87, $7c, $81, $48, $85, $7b, $87, $7a, $85, $79, $87, $78, $87, $77, $87, $76, $85, $75, $85, $4e, $ff, $29
	.byte $41, $0d
	.word @song0ref1125
	.byte $41, $11
	.word @song0ref751
	.byte $76, $85, $75, $87, $74, $87, $73, $87, $72, $85, $71, $87, $00, $ff, $c9, $48, $f7, $42
	.word @song0ch0loop
@song0ch1:
@song0ch1loop:
	.byte $76, $82
@song0ref1891:
	.byte $19, $95, $1d, $95, $20, $95, $4e, $ff, $25, $95, $4e, $00, $20, $95, $1d, $95
	.byte $41, $0c
	.word @song0ref1891
@song0ref1910:
	.byte $4e, $01, $16, $95, $4e, $00, $19, $95, $1d, $95
@song0ref1920:
	.byte $22, $95
@song0ref1922:
	.byte $1d, $95, $19, $95, $4e, $01, $16, $95, $4e, $00, $19, $95, $1d, $95, $22, $83, $91
@song0ref1939:
	.byte $1d, $95, $19
@song0ref1942:
	.byte $95
@song0ref1943:
	.byte $12, $95, $4e, $01, $16, $95, $4e, $00, $19, $95, $1e, $95, $19, $95, $4e, $01, $16, $95, $4e, $00
	.byte $41, $0c
	.word @song0ref1943
@song0ref1966:
	.byte $4e, $00
@song0ref1968:
	.byte $14
@song0ref1969:
	.byte $95
@song0ref1970:
	.byte $18, $95, $1b, $95, $20, $95, $1b, $95, $18, $95, $14, $89, $8b
	.byte $41, $0a
	.word @song0ref1970
	.byte $41, $0c
	.word @song0ref1891
	.byte $41, $0c
	.word @song0ref1891
	.byte $4e, $01, $16, $95, $4e, $00, $19, $95, $1d, $95, $22, $8f, $85
	.byte $41, $0b
	.word @song0ref1922
@song0ref2008:
	.byte $95, $1d, $95, $19
@song0ref2012:
	.byte $95
@song0ref2013:
	.byte $11, $95, $14, $95, $18, $95, $1d, $95, $18, $95, $14
	.byte $41, $0c
	.word @song0ref2012
	.byte $ad
	.byte $41, $0b
	.word @song0ref1970
	.byte $41, $0b
	.word @song0ref1969
	.byte $41, $0c
	.word @song0ref1891
	.byte $19, $95, $1d, $95, $20, $95, $4e, $ff, $25, $95, $4e, $00, $20, $83, $91, $1d, $95
	.byte $41, $13
	.word @song0ref1910
	.byte $95
	.byte $41, $10
	.word @song0ref1939
	.byte $4e, $00, $12, $95, $4e, $01, $16, $89, $8b, $4e, $00, $19, $95, $1e, $95, $19, $95, $4e, $01, $16, $95
	.byte $41, $0d
	.word @song0ref1966
	.byte $41, $0b
	.word @song0ref1969
	.byte $19, $95, $1d, $95, $20, $95, $4e, $ff, $25, $95, $4e, $00, $20, $8f, $85, $1d, $95
	.byte $41, $0c
	.word @song0ref1891
	.byte $41, $13
	.word @song0ref1910
	.byte $41, $10
	.word @song0ref2008
	.byte $41, $0c
	.word @song0ref2012
	.byte $ad
	.byte $41, $0b
	.word @song0ref1970
	.byte $41, $0a
	.word @song0ref1969
	.byte $83, $91
	.byte $41, $0c
	.word @song0ref1891
	.byte $41, $0c
	.word @song0ref1891
	.byte $41, $0d
	.word @song0ref1968
	.byte $95, $18, $95, $1b, $89, $8b, $20, $95, $1b, $95, $18, $95
	.byte $41, $0c
	.word @song0ref1891
	.byte $41, $0c
	.word @song0ref1891
	.byte $41, $0a
	.word @song0ref2013
	.byte $20, $8f, $85
	.byte $41, $0b
	.word @song0ref2013
	.byte $95, $12, $95, $4e, $01, $16, $95, $4e, $00, $19, $95, $1e, $95, $4e, $01, $0d, $95, $16, $95, $4e, $00
	.byte $41, $0c
	.word @song0ref1943
	.byte $41, $0d
	.word @song0ref1966
	.byte $41, $0b
	.word @song0ref1969
	.byte $41, $0c
	.word @song0ref1891
	.byte $41, $0c
	.word @song0ref1891
	.byte $19, $83, $91
@song0ref2201:
	.byte $1d, $95, $20, $95, $4e, $ff, $23, $95, $4e, $00, $20, $95, $1d, $95, $19, $95
	.byte $41, $0a
	.word @song0ref2201
	.byte $41, $0c
	.word @song0ref1943
	.byte $4e, $00, $14, $95, $18, $95, $1b, $95, $1e, $89, $8b, $1b, $95, $18
	.byte $41, $0d
	.word @song0ref1942
@song0ref2240:
	.byte $10, $95, $4e, $00, $14, $95, $17, $95, $1c, $95, $17, $95, $14
	.byte $41, $0d
	.word @song0ref1942
	.byte $4e, $00, $14, $8f, $85
@song0ref2261:
	.byte $18, $95, $1b, $95, $1e, $95, $1b, $95, $18, $95
	.byte $41, $0c
	.word @song0ref1891
	.byte $19, $95
	.byte $41, $0a
	.word @song0ref2201
	.byte $41, $0c
	.word @song0ref1943
	.byte $4e, $00, $14, $95
	.byte $41, $0a
	.word @song0ref2261
	.byte $41, $0c
	.word @song0ref1943
	.byte $41, $0b
	.word @song0ref2240
	.byte $95, $12, $95, $4e, $01, $16, $83, $91, $4e, $00, $19, $95, $1e, $95, $19, $95, $4e, $01, $16, $95, $4e, $00, $14, $95
	.byte $41, $0a
	.word @song0ref2261
	.byte $41, $0c
	.word @song0ref1891
	.byte $19, $95, $1d, $95, $20, $95, $4e, $ff, $25, $95, $4e, $00, $20, $89, $8b, $1d, $97
	.byte $41, $0c
	.word @song0ref1891
	.byte $41, $0c
	.word @song0ref1891
	.byte $41, $0f
	.word @song0ref1910
	.byte $8d, $87, $1d, $95, $22, $95
	.byte $41, $10
	.word @song0ref1939
	.byte $4e, $00
	.byte $41, $0c
	.word @song0ref1943
	.byte $4e, $00, $14, $95, $18, $95, $1b, $95, $20, $95, $1b, $93, $81, $18, $95
	.byte $41, $0c
	.word @song0ref1968
	.byte $41, $0c
	.word @song0ref1891
	.byte $41, $0c
	.word @song0ref1891
	.byte $4e, $01, $16, $95, $4e, $00, $19, $95, $1d, $81, $93
	.byte $41, $0d
	.word @song0ref1920
	.byte $41, $10
	.word @song0ref2008
	.byte $41, $0c
	.word @song0ref2012
	.byte $87, $a5
	.byte $41, $0b
	.word @song0ref1970
	.byte $41, $0b
	.word @song0ref1969
	.byte $41, $0c
	.word @song0ref1891
	.byte $19, $95, $1d, $95, $20, $8d, $87, $4e, $ff, $25, $95, $4e, $00, $20, $95, $1d, $95
	.byte $41, $13
	.word @song0ref1910
	.byte $95
	.byte $41, $0f
	.word @song0ref1939
	.byte $93, $81, $4e, $00
	.byte $41, $0c
	.word @song0ref1943
	.byte $41, $0d
	.word @song0ref1966
	.byte $41, $0b
	.word @song0ref1969
	.byte $19, $95, $1d, $95, $20, $95, $4e, $ff, $25, $81, $93, $4e, $00, $20, $95, $1d, $95
	.byte $41, $0c
	.word @song0ref1891
	.byte $41, $13
	.word @song0ref1910
	.byte $95, $1d, $95, $19, $95, $11, $87, $8d, $14, $95, $18, $95, $1d, $95, $18, $95, $14
	.byte $41, $0c
	.word @song0ref2012
	.byte $ad
	.byte $41, $0b
	.word @song0ref1970
	.byte $95, $18, $95, $1b, $95, $20, $8d, $87, $1b, $95, $18, $95
	.byte $41, $0c
	.word @song0ref1891
	.byte $41, $0c
	.word @song0ref1891
	.byte $41, $0d
	.word @song0ref1968
	.byte $93, $81, $18, $95, $1b, $95, $20, $95, $1b, $95, $18, $93, $42
	.word @song0ch1loop
@song0ch2:
@song0ch2loop:
	.byte $80, $19, $ff, $ff, $9d, $4e, $01, $16, $ff, $db, $c1, $4e, $00, $12, $ff, $ff, $9d, $14, $ff, $99, $ff, $83, $19, $ff
	.byte $ff, $9d, $4e, $01, $16, $d7, $ff, $c5, $4e, $00, $11, $ff, $ff, $9d, $14, $95, $af
@song0ref2582:
	.byte $20, $c5, $24, $c5, $27, $c5, $1d, $ff, $8d, $20, $c5, $4e, $ff, $25, $9b, $f1, $4e, $00, $1d, $c5, $22, $c5, $4e, $ff
	.byte $25, $ff, $8d, $4e, $00, $1e, $c5, $27, $a1, $a3
@song0ref2616:
	.byte $4e, $ff, $25, $c5, $4e, $00, $24, $c5, $20, $c5, $4e, $ff, $29, $c5, $4e, $00, $27, $c5, $00, $c5, $1d, $a7, $9d
@song0ref2639:
	.byte $20, $c5, $4e, $ff, $25, $ff, $8d, $4e, $00, $1d, $c5, $22, $c5, $4e, $ff, $25, $c5, $4e, $00, $20, $ad, $ff, $ef, $27
	.byte $ff, $ff, $8b, $91, $4e, $ff, $25, $ff, $ff, $9d, $4e, $00, $24, $c5, $20, $c5, $24, $b9, $8b, $27, $c5, $19, $ff, $ff
	.byte $9d, $1d, $ff, $87, $ff, $95, $1e, $ff, $ff, $9d, $20, $c5, $ff, $d7, $19, $ff, $ff, $9d, $00, $83, $ff, $ff, $99, $12
	.byte $ff, $8d, $14, $d1, $bb, $4e, $01, $16, $ff, $8d, $4e, $00, $17, $ff, $8d, $12, $ff, $8d, $14, $8f, $fd, $19, $ff, $8d
	.byte $17, $ff, $8d, $12, $dd, $af, $14, $ff, $8d, $4e, $01, $16, $ff, $8d, $4e, $00, $17, $ff, $8d, $12, $9b, $f1, $14, $ff
	.byte $8d, $19, $ff, $f9, $ff, $ff, $c5, $4e, $01, $16, $ff, $b5, $e7, $4e, $00, $12, $ff, $ff, $9d, $14, $f3, $ff, $a9, $19
	.byte $ff, $ff, $9d, $4e, $01, $16, $b1, $ff, $eb, $4e, $00, $11, $ff, $ff, $8f, $8d, $14, $c5
	.byte $41, $0a
	.word @song0ref2582
	.byte $bd, $87, $4e, $ff, $25, $ff, $8d, $4e, $00, $1d, $c5, $22, $c5, $4e, $ff, $25, $ff, $8d, $4e, $00, $1e, $c3, $81, $27
	.byte $c5
	.byte $41, $0d
	.word @song0ref2616
	.byte $81, $c3
	.byte $41, $0c
	.word @song0ref2639
	.byte $87, $ff, $ff, $95, $27, $ff, $e5, $b7, $4e, $ff, $25, $ff, $ff, $9d, $4e, $00, $24, $c5, $20, $c5, $24, $93, $b1, $27
	.byte $c3, $42
	.word @song0ch2loop
@song0ch3:
@song0ch3loop:
	.byte $7d, $80
@song0ref2868:
	.byte $20
@song0ref2869:
	.byte $7b, $81, $79, $81, $77, $81, $75, $81, $73, $81, $71
@song0ref2880:
	.byte $81, $00
@song0ref2882:
	.byte $87
@song0ref2883:
	.byte $7d, $23, $7b, $81, $79, $81, $77, $81, $75, $81, $73, $81, $71, $81, $00, $87, $7d, $23
	.byte $41, $12
	.word @song0ref2869
	.byte $41, $11
	.word @song0ref2869
	.byte $7d
	.byte $41, $13
	.word @song0ref2868
	.byte $41, $12
	.word @song0ref2869
	.byte $41, $11
	.word @song0ref2869
	.byte $7d, $20
@song0ref2919:
	.byte $7b, $81, $79, $81, $77, $81, $75
@song0ref2926:
	.byte $81
@song0ref2927:
	.byte $74
@song0ref2928:
	.byte $81, $72, $81, $00, $87, $7e, $23, $7c, $81, $7a, $81, $78, $81, $76, $81, $74, $81, $72
	.byte $41, $0d
	.word @song0ref2880
	.byte $41, $12
	.word @song0ref2869
	.byte $7b, $81, $79, $81, $77, $81, $75, $81, $73, $81, $71, $81, $00, $87, $7d
	.byte $41, $13
	.word @song0ref2868
	.byte $41, $12
	.word @song0ref2869
	.byte $41, $11
	.word @song0ref2869
	.byte $7d
	.byte $41, $13
	.word @song0ref2868
	.byte $41, $12
	.word @song0ref2869
	.byte $41, $11
	.word @song0ref2869
	.byte $7d
	.byte $41, $13
	.word @song0ref2868
	.byte $41, $12
	.word @song0ref2869
	.byte $41, $11
	.word @song0ref2869
	.byte $7d
	.byte $41, $0f
	.word @song0ref2868
	.byte $72, $81, $00, $87, $7e, $23, $7c, $81, $7a, $81, $78, $81, $76, $81, $74, $81, $72
	.byte $41, $0d
	.word @song0ref2880
	.byte $41, $11
	.word @song0ref2869
	.byte $7d
	.byte $41, $13
	.word @song0ref2868
	.byte $41, $12
	.word @song0ref2869
	.byte $41, $11
	.word @song0ref2869
	.byte $7d
	.byte $41, $13
	.word @song0ref2868
	.byte $41, $12
	.word @song0ref2869
	.byte $41, $11
	.word @song0ref2869
	.byte $7d
	.byte $41, $13
	.word @song0ref2868
	.byte $41, $12
	.word @song0ref2869
	.byte $41, $11
	.word @song0ref2869
	.byte $7d
	.byte $41, $13
	.word @song0ref2868
@song0ref3057:
	.byte $7b, $81, $79, $81, $77, $81, $75, $81, $73, $81, $71, $81, $00, $87, $7e, $23, $7c, $81, $7a, $81, $78, $81, $76, $81
	.byte $74, $81, $72, $81, $00, $81, $85
	.byte $41, $0a
	.word @song0ref2883
	.byte $7b, $81, $79, $81, $77, $81, $75, $81, $73, $81, $71, $81, $00, $87, $7d
	.byte $41, $13
	.word @song0ref2868
	.byte $41, $12
	.word @song0ref2869
	.byte $41, $11
	.word @song0ref2869
	.byte $7d
	.byte $41, $13
	.word @song0ref2868
	.byte $41, $12
	.word @song0ref2869
	.byte $41, $11
	.word @song0ref2869
	.byte $7d
	.byte $41, $13
	.word @song0ref2868
	.byte $41, $12
	.word @song0ref2869
	.byte $41, $11
	.word @song0ref2869
	.byte $7d
	.byte $41, $13
	.word @song0ref2868
	.byte $41, $11
	.word @song0ref2869
	.byte $7e, $23, $7c, $81, $7a, $81, $78, $81, $76, $81, $74, $81, $72
	.byte $41, $0c
	.word @song0ref2880
	.byte $7d
	.byte $41, $13
	.word @song0ref2868
	.byte $41, $12
	.word @song0ref2869
	.byte $41, $11
	.word @song0ref2869
	.byte $7d
	.byte $41, $13
	.word @song0ref2868
	.byte $41, $12
	.word @song0ref2869
	.byte $41, $11
	.word @song0ref2869
	.byte $7d
	.byte $41, $13
	.word @song0ref2868
	.byte $41, $12
	.word @song0ref2869
	.byte $41, $11
	.word @song0ref2869
	.byte $7d
	.byte $41, $13
	.word @song0ref2868
	.byte $41, $12
	.word @song0ref2869
	.byte $41, $10
	.word @song0ref3057
	.byte $87, $7e, $20, $7c, $81, $7a, $81, $78, $81, $76, $81, $74, $81, $72
	.byte $41, $0d
	.word @song0ref2880
	.byte $41, $12
	.word @song0ref2869
	.byte $41, $11
	.word @song0ref2869
	.byte $7d
	.byte $41, $13
	.word @song0ref2868
	.byte $41, $12
	.word @song0ref2869
	.byte $41, $11
	.word @song0ref2869
	.byte $7d
	.byte $41, $13
	.word @song0ref2868
	.byte $41, $12
	.word @song0ref2869
	.byte $41, $11
	.word @song0ref2869
	.byte $7d
	.byte $41, $13
	.word @song0ref2868
	.byte $41, $12
	.word @song0ref2869
	.byte $41, $11
	.word @song0ref2869
	.byte $7e, $20, $7c, $81, $7a, $81, $78, $81, $76
	.byte $41, $0b
	.word @song0ref2926
	.byte $72
	.byte $41, $0d
	.word @song0ref2880
	.byte $41, $12
	.word @song0ref2869
	.byte $7b, $81, $79, $81, $77, $81, $75, $81, $73, $81, $71, $81, $00, $87, $7d
	.byte $41, $13
	.word @song0ref2868
	.byte $41, $12
	.word @song0ref2869
@song0ref3291:
	.byte $7b, $81, $79, $81, $77, $81, $75, $81, $73, $81, $71, $81, $00, $81, $85, $7d, $23, $7b, $81, $79, $81, $77, $81, $75
	.byte $81, $73, $81, $71, $81, $00, $87, $7d
	.byte $41, $13
	.word @song0ref2868
	.byte $41, $12
	.word @song0ref2869
	.byte $41, $11
	.word @song0ref2869
	.byte $7d
	.byte $41, $13
	.word @song0ref2868
	.byte $41, $12
	.word @song0ref2869
	.byte $41, $11
	.word @song0ref2869
	.byte $7d
	.byte $41, $0a
	.word @song0ref2868
	.byte $7c, $81, $7a, $81, $78, $81, $76
	.byte $41, $0b
	.word @song0ref2926
	.byte $72
	.byte $41, $0d
	.word @song0ref2880
	.byte $41, $11
	.word @song0ref2869
	.byte $7d
	.byte $41, $13
	.word @song0ref2868
	.byte $41, $12
	.word @song0ref2869
	.byte $41, $11
	.word @song0ref2869
	.byte $7d
	.byte $41, $13
	.word @song0ref2868
	.byte $41, $12
	.word @song0ref2869
	.byte $41, $11
	.word @song0ref2869
	.byte $7d
	.byte $41, $13
	.word @song0ref2868
	.byte $41, $12
	.word @song0ref2869
	.byte $41, $11
	.word @song0ref2869
	.byte $7d
	.byte $41, $13
	.word @song0ref2868
	.byte $7b, $81, $7a, $81, $78, $81, $76
	.byte $41, $0b
	.word @song0ref2926
	.byte $72
	.byte $41, $0d
	.word @song0ref2880
	.byte $7b, $81, $79, $81, $77, $81, $75, $81, $73, $81, $71, $81, $00, $87, $7d
	.byte $41, $13
	.word @song0ref2868
	.byte $41, $12
	.word @song0ref2869
	.byte $41, $11
	.word @song0ref2869
	.byte $7d
	.byte $41, $13
	.word @song0ref2868
	.byte $41, $12
	.word @song0ref2869
	.byte $41, $11
	.word @song0ref2869
	.byte $7d
	.byte $41, $13
	.word @song0ref2868
	.byte $41, $12
	.word @song0ref2869
	.byte $41, $11
	.word @song0ref2869
	.byte $7d
	.byte $41, $13
	.word @song0ref2868
	.byte $41, $0b
	.word @song0ref2869
	.byte $78, $81, $76
	.byte $41, $0b
	.word @song0ref2926
	.byte $72
	.byte $41, $0c
	.word @song0ref2880
	.byte $7d
	.byte $41, $13
	.word @song0ref2868
	.byte $41, $12
	.word @song0ref2869
	.byte $41, $11
	.word @song0ref2869
	.byte $7d
	.byte $41, $13
	.word @song0ref2868
	.byte $41, $12
	.word @song0ref2869
	.byte $41, $11
	.word @song0ref2869
	.byte $7d
	.byte $41, $13
	.word @song0ref2868
	.byte $41, $12
	.word @song0ref2869
	.byte $41, $10
	.word @song0ref2869
	.byte $81, $85, $7d
	.byte $41, $13
	.word @song0ref2868
	.byte $41, $12
	.word @song0ref2869
	.byte $41, $0e
	.word @song0ref2919
	.byte $72, $81, $00, $87, $7d
	.byte $41, $13
	.word @song0ref2868
	.byte $41, $12
	.word @song0ref2869
	.byte $41, $11
	.word @song0ref2869
	.byte $7d
	.byte $41, $13
	.word @song0ref2868
	.byte $41, $12
	.word @song0ref2869
	.byte $41, $11
	.word @song0ref2869
	.byte $7d
	.byte $41, $13
	.word @song0ref2868
	.byte $41, $12
	.word @song0ref2869
	.byte $41, $11
	.word @song0ref2869
	.byte $7d
	.byte $41, $13
	.word @song0ref2868
	.byte $41, $12
	.word @song0ref2869
	.byte $41, $0e
	.word @song0ref2869
	.byte $72, $81, $00, $87, $7e, $20, $7c, $81, $7a, $81, $78, $81, $76, $81, $74, $81, $72
	.byte $41, $0d
	.word @song0ref2880
	.byte $41, $12
	.word @song0ref2869
	.byte $41, $11
	.word @song0ref2869
	.byte $7d
	.byte $41, $13
	.word @song0ref2868
	.byte $41, $12
	.word @song0ref2869
	.byte $41, $11
	.word @song0ref2869
	.byte $7d
	.byte $41, $13
	.word @song0ref2868
	.byte $41, $12
	.word @song0ref2869
	.byte $41, $11
	.word @song0ref2869
	.byte $7d
	.byte $41, $13
	.word @song0ref2868
	.byte $41, $12
	.word @song0ref2869
	.byte $41, $11
	.word @song0ref2869
	.byte $7d, $20
	.byte $41, $10
	.word @song0ref3057
	.byte $41, $0b
	.word @song0ref2882
	.byte $41, $12
	.word @song0ref2869
	.byte $7b, $81, $79, $81, $77, $81, $75, $81, $73, $81, $71, $81, $00, $87, $7d
	.byte $41, $13
	.word @song0ref2868
	.byte $41, $12
	.word @song0ref2869
	.byte $41, $11
	.word @song0ref2869
	.byte $7d
	.byte $41, $13
	.word @song0ref2868
	.byte $41, $12
	.word @song0ref2869
	.byte $41, $11
	.word @song0ref2869
	.byte $7d
	.byte $41, $13
	.word @song0ref2868
	.byte $41, $12
	.word @song0ref2869
	.byte $41, $11
	.word @song0ref2869
	.byte $7d
	.byte $41, $12
	.word @song0ref2868
	.byte $7e, $23, $7c, $81, $7a, $81, $78, $81, $76, $81, $74, $81, $72
	.byte $41, $0d
	.word @song0ref2880
	.byte $41, $11
	.word @song0ref2869
	.byte $7d, $20
	.byte $41, $12
	.word @song0ref3291
	.byte $41, $0a
	.word @song0ref2883
	.byte $41, $12
	.word @song0ref2869
	.byte $7b, $81, $79, $81, $77, $81, $75, $81, $73, $81, $71, $81, $00, $87, $7d
	.byte $41, $13
	.word @song0ref2868
	.byte $41, $12
	.word @song0ref2869
	.byte $41, $11
	.word @song0ref2869
	.byte $7d
	.byte $41, $13
	.word @song0ref2868
	.byte $41, $12
	.word @song0ref2869
	.byte $41, $11
	.word @song0ref2869
	.byte $7d
	.byte $41, $13
	.word @song0ref2868
	.byte $41, $10
	.word @song0ref3057
	.byte $87, $7e, $23, $7c, $81, $7a, $81, $78, $81, $76, $81, $74, $81, $72
	.byte $41, $0c
	.word @song0ref2880
	.byte $7d
	.byte $41, $13
	.word @song0ref2868
	.byte $41, $12
	.word @song0ref2869
	.byte $41, $11
	.word @song0ref2869
	.byte $7d
	.byte $41, $13
	.word @song0ref2868
	.byte $41, $12
	.word @song0ref2869
	.byte $41, $11
	.word @song0ref2869
	.byte $7d
	.byte $41, $13
	.word @song0ref2868
	.byte $41, $12
	.word @song0ref2869
	.byte $41, $11
	.word @song0ref2869
	.byte $7d
	.byte $41, $13
	.word @song0ref2868
	.byte $41, $11
	.word @song0ref2869
	.byte $7e, $23, $7c, $81, $7a, $81, $78, $81, $76
	.byte $41, $0b
	.word @song0ref2926
	.byte $72, $81, $00, $87, $7d
	.byte $41, $13
	.word @song0ref2868
	.byte $41, $12
	.word @song0ref2869
	.byte $41, $11
	.word @song0ref2869
	.byte $7d
	.byte $41, $13
	.word @song0ref2868
	.byte $41, $12
	.word @song0ref2869
	.byte $41, $11
	.word @song0ref2869
	.byte $7d
	.byte $41, $13
	.word @song0ref2868
	.byte $41, $12
	.word @song0ref2869
	.byte $41, $10
	.word @song0ref2869
	.byte $89, $7d
	.byte $41, $13
	.word @song0ref2868
	.byte $41, $12
	.word @song0ref2869
	.byte $41, $10
	.word @song0ref3057
	.byte $87, $7e, $20, $7c, $81, $7a, $81, $78, $81, $76, $81, $74, $81, $72
	.byte $41, $0d
	.word @song0ref2880
	.byte $41, $12
	.word @song0ref2869
	.byte $41, $11
	.word @song0ref2869
	.byte $7d
	.byte $41, $13
	.word @song0ref2868
	.byte $41, $12
	.word @song0ref2869
	.byte $41, $11
	.word @song0ref2869
	.byte $7d
	.byte $41, $13
	.word @song0ref2868
	.byte $41, $12
	.word @song0ref2869
	.byte $41, $11
	.word @song0ref2869
	.byte $7d
	.byte $41, $13
	.word @song0ref2868
	.byte $41, $12
	.word @song0ref2869
	.byte $41, $11
	.word @song0ref2869
	.byte $7d, $20, $7c, $81, $7a, $81, $78, $81, $76
	.byte $41, $0b
	.word @song0ref2926
	.byte $72
	.byte $41, $0d
	.word @song0ref2880
	.byte $41, $12
	.word @song0ref2869
	.byte $7b, $81, $79, $81, $77, $81, $75, $81, $73, $81, $71, $81, $00, $87, $7d
	.byte $41, $13
	.word @song0ref2868
	.byte $41, $12
	.word @song0ref2869
@song0ref3948:
	.byte $7b, $81, $79, $81, $77, $81, $75, $81, $73, $81, $71, $81, $00, $85, $81, $7d, $23, $7b, $81, $79, $81, $77, $81, $75
	.byte $81, $73, $81, $71, $81, $00, $87, $7d
	.byte $41, $13
	.word @song0ref2868
	.byte $41, $12
	.word @song0ref2869
	.byte $41, $11
	.word @song0ref2869
	.byte $7d
	.byte $41, $13
	.word @song0ref2868
	.byte $41, $12
	.word @song0ref2869
	.byte $41, $11
	.word @song0ref2869
	.byte $7d
	.byte $41, $0b
	.word @song0ref2868
	.byte $7a, $81, $78, $81, $76
	.byte $41, $0b
	.word @song0ref2926
	.byte $72
	.byte $41, $0d
	.word @song0ref2880
	.byte $41, $11
	.word @song0ref2869
	.byte $7d
	.byte $41, $13
	.word @song0ref2868
	.byte $41, $12
	.word @song0ref2869
	.byte $41, $11
	.word @song0ref2869
	.byte $7d
	.byte $41, $13
	.word @song0ref2868
	.byte $41, $12
	.word @song0ref2869
	.byte $41, $11
	.word @song0ref2869
	.byte $7d
	.byte $41, $13
	.word @song0ref2868
	.byte $41, $12
	.word @song0ref2869
	.byte $41, $11
	.word @song0ref2869
	.byte $7d
	.byte $41, $13
	.word @song0ref2868
	.byte $7b, $81, $79, $81, $78, $81, $76
	.byte $41, $0b
	.word @song0ref2926
	.byte $72
	.byte $41, $0d
	.word @song0ref2880
	.byte $7b, $81, $79, $81, $77, $81, $75, $81, $73, $81, $71, $81, $00, $87, $7d
	.byte $41, $13
	.word @song0ref2868
	.byte $41, $12
	.word @song0ref2869
	.byte $41, $11
	.word @song0ref2869
	.byte $7d
	.byte $41, $13
	.word @song0ref2868
	.byte $41, $12
	.word @song0ref2869
	.byte $41, $11
	.word @song0ref2869
	.byte $7d
	.byte $41, $13
	.word @song0ref2868
	.byte $41, $12
	.word @song0ref2869
	.byte $41, $11
	.word @song0ref2869
	.byte $7d
	.byte $41, $13
	.word @song0ref2868
	.byte $41, $0d
	.word @song0ref2869
	.byte $41, $0a
	.word @song0ref2927
	.byte $72
	.byte $41, $0c
	.word @song0ref2880
	.byte $7d
	.byte $41, $13
	.word @song0ref2868
	.byte $41, $12
	.word @song0ref2869
	.byte $41, $11
	.word @song0ref2869
	.byte $7d
	.byte $41, $13
	.word @song0ref2868
	.byte $41, $12
	.word @song0ref2869
	.byte $41, $11
	.word @song0ref2869
	.byte $7d
	.byte $41, $13
	.word @song0ref2868
	.byte $41, $12
	.word @song0ref2869
	.byte $41, $10
	.word @song0ref2869
	.byte $85, $81, $7d
	.byte $41, $13
	.word @song0ref2868
	.byte $41, $12
	.word @song0ref2869
	.byte $7b, $81, $79, $81, $77, $81, $75, $81, $73
	.byte $41, $0a
	.word @song0ref2928
	.byte $72, $81, $00, $87, $7e, $20, $7c, $81, $7a, $81, $78, $81, $76, $81, $74, $81, $72
	.byte $41, $0d
	.word @song0ref2880
	.byte $41, $12
	.word @song0ref2869
	.byte $41, $11
	.word @song0ref2869
	.byte $7d
	.byte $41, $13
	.word @song0ref2868
	.byte $41, $12
	.word @song0ref2869
	.byte $41, $11
	.word @song0ref2869
	.byte $7d
	.byte $41, $13
	.word @song0ref2868
	.byte $41, $12
	.word @song0ref2869
	.byte $41, $11
	.word @song0ref2869
	.byte $7d
	.byte $41, $13
	.word @song0ref2868
	.byte $41, $12
	.word @song0ref2869
	.byte $41, $11
	.word @song0ref2869
	.byte $7e, $20, $7c, $81, $7a, $81, $78, $81, $76, $81, $74, $81, $72
	.byte $41, $0d
	.word @song0ref2880
	.byte $41, $12
	.word @song0ref2869
	.byte $41, $11
	.word @song0ref2869
	.byte $7d
	.byte $41, $13
	.word @song0ref2868
	.byte $41, $12
	.word @song0ref2869
	.byte $41, $11
	.word @song0ref2869
	.byte $7d
	.byte $41, $13
	.word @song0ref2868
	.byte $41, $12
	.word @song0ref2869
	.byte $41, $11
	.word @song0ref2869
	.byte $7d
	.byte $41, $13
	.word @song0ref2868
	.byte $41, $12
	.word @song0ref2869
	.byte $41, $11
	.word @song0ref2869
	.byte $7d, $20
	.byte $41, $10
	.word @song0ref3057
	.byte $41, $0b
	.word @song0ref2882
	.byte $41, $12
	.word @song0ref2869
	.byte $7b, $81, $79, $81, $77, $81, $75, $81, $73, $81, $71, $81, $00, $87, $7d
	.byte $41, $13
	.word @song0ref2868
	.byte $41, $12
	.word @song0ref2869
	.byte $41, $11
	.word @song0ref2869
	.byte $7d
	.byte $41, $13
	.word @song0ref2868
	.byte $41, $12
	.word @song0ref2869
	.byte $41, $11
	.word @song0ref2869
	.byte $7d
	.byte $41, $13
	.word @song0ref2868
	.byte $41, $12
	.word @song0ref2869
	.byte $41, $11
	.word @song0ref2869
	.byte $7d
	.byte $41, $12
	.word @song0ref2868
	.byte $7e, $23, $7c, $81, $7a, $81, $78, $81, $76
	.byte $41, $0b
	.word @song0ref2926
	.byte $72
	.byte $41, $0d
	.word @song0ref2880
	.byte $7b, $81, $79, $81, $77, $81, $75, $81, $73, $81, $71, $81, $00, $87, $7d, $20
	.byte $41, $12
	.word @song0ref3948
	.byte $41, $0a
	.word @song0ref2883
	.byte $41, $12
	.word @song0ref2869
	.byte $7b, $81, $79, $81, $77, $81, $75, $81, $73, $81, $71, $81, $00, $85, $42
	.word @song0ch3loop
@song0ch4:
@song0ch4loop:
@song0ref4401:
	.byte $ff, $ff, $ff, $fd, $ff, $ff, $ff, $fd, $ff, $ff, $ff, $fd
	.byte $41, $0c
	.word @song0ref4401
	.byte $41, $0c
	.word @song0ref4401
	.byte $41, $0c
	.word @song0ref4401
	.byte $41, $0c
	.word @song0ref4401
	.byte $41, $0c
	.word @song0ref4401
	.byte $41, $0c
	.word @song0ref4401
	.byte $41, $0c
	.word @song0ref4401
	.byte $41, $0c
	.word @song0ref4401
	.byte $ff, $ff, $ff, $fd, $f7, $42
	.word @song0ch4loop
